=== sunc33/documents-structures/devoir-01/livres.dtd
<!ELEMENT livres (livre+)>
<!ELEMENT livre (titre,auteur,date)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST livre id ID #REQUIRED>
<!ATTLIST livre lang CDATA #REQUIRED>

=== sunc33/documents-structures/devoir-01/livres.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE livres SYSTEM "livres.dtd">

<livres>
	<livre id="l1" lang="chinois">
		<titre>Vivre!</titre>
		<auteur>YU Hua</auteur>
		<date>1994</date>
	</livre>
	<livre id="l2" lang="chinois">
		<titre>La dure loi du karma</titre>
		<auteur>MO Yan</auteur>
		<date>2008</date>
	</livre>
	<livre id="l3" lang="franÃ§ais">
		<titre>Germinal</titre>
		<auteur>Emile Zola</auteur>
		<date>1885</date>
	</livre>
</livres>
